# Generated by Django 4.2.7 on 2025-11-18 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WindLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('lat_min', models.FloatField()),
                ('lat_max', models.FloatField()),
                ('lon_min', models.FloatField()),
                ('lon_max', models.FloatField()),
                ('num_turbines', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wind_locations',
            },
        ),
        migrations.CreateModel(
            name='AIModelResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('optimal_points', models.JSONField()),
                ('energy_1_month', models.FloatField()),
                ('energy_3_months', models.FloatField()),
                ('energy_6_months', models.FloatField()),
                ('energy_12_months', models.FloatField()),
                ('avg_wind_speed', models.FloatField()),
                ('avg_elevation', models.FloatField()),
                ('soil_types', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wind_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimization.windlocation')),
            ],
            options={
                'db_table': 'ai_model_results',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('elevation', models.FloatField()),
                ('slope', models.FloatField(null=True)),
                ('soil_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wind_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimization.windlocation')),
            ],
            options={
                'db_table': 'environmental_data',
                'indexes': [models.Index(fields=['wind_location', 'latitude', 'longitude'], name='environment_wind_lo_ac8dbd_idx')],
            },
        ),
    ]
