# Generated by Django 4.2.7 on 2025-11-18 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('optimization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelresult',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aimodelresult',
            name='wind_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='optimization.windlocation'),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='slope',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='wind_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_points', to='optimization.windlocation'),
        ),
        migrations.AlterField(
            model_name='windlocation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='windlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wind_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
