# Generated by Django 4.2.7 on 2026-04-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='energyoffer',
            new_name='energy_offe_status_0b7188_idx',
            old_name='energy_offers_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='energyoffer',
            new_name='energy_offe_seller__7f6333_idx',
            old_name='energy_offers_seller_status_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_seller__380387_idx',
            old_name='transactions_seller_created_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_buyer_i_fb4621_idx',
            old_name='transactions_buyer_created_idx',
        ),
    ]
